apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tinai-devportal
  namespace: tinai-system
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
spec:
  ingressClassName: traefik
  rules:
    - host: dev.tinai.cloud
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: tinai-devportal
                port:
                  number: 80
