apiVersion: v1
kind: Service
metadata:
  name: tinai-devportal
  namespace: tinai-system
  labels:
    app: tinai-devportal
spec:
  type: ClusterIP
  selector:
    app: tinai-devportal
  ports:
    - name: http
      port: 80
      targetPort: 3030
      protocol: TCP
