apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: falco-sidekick-secrets
  namespace: tinai-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: falco-sidekick-secrets
    creationPolicy: Owner
  data:
    - secretKey: slack_webhook_url
      remoteRef:
        key: secret/tinai/alerting
        property: slack_webhook_url
    - secretKey: pagerduty_routing_key
      remoteRef:
        key: secret/tinai/alerting
        property: pagerduty_routing_key
