apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: forgejo-registry
  namespace: tinai-system
  annotations:
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  ingressClassName: traefik
  rules:
    - host: registry.tinai.cloud
      http:
        paths:
          - path: /v2
            pathType: Prefix
            backend:
              service:
                name: forgejo
                port:
                  number: 3000
