apiVersion: v1
kind: Namespace
metadata:
  name: tinai-storage
  labels:
    app.kubernetes.io/part-of: tinai
---
apiVersion: v1
kind: Namespace
metadata:
  name: tinai-databases
  labels:
    app.kubernetes.io/part-of: tinai
