apiVersion: v1
kind: ServiceAccount
metadata:
  name: tinai-storage-provisioner-sa
  namespace: tinai-storage
  labels:
    app.kubernetes.io/name: tinai-storage-provisioner
    app.kubernetes.io/part-of: tinai
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tinai-storage-provisioner
  labels:
    app.kubernetes.io/name: tinai-storage-provisioner
    app.kubernetes.io/part-of: tinai
rules:
  - apiGroups:
      - postgresql.cnpg.io
    resources:
      - clusters
    verbs:
      - create
      - get
      - list
      - watch
      - update
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tinai-storage-provisioner
  labels:
    app.kubernetes.io/name: tinai-storage-provisioner
    app.kubernetes.io/part-of: tinai
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tinai-storage-provisioner
subjects:
  - kind: ServiceAccount
    name: tinai-storage-provisioner-sa
    namespace: tinai-storage
