apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
patches:
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/args
        value:
          - /usr/local/bin/argocd-server
          - --insecure   # TLS terminated at ingress
    target:
      kind: Deployment
      name: argocd-server
