# ESO ExternalSecret for Woodpecker credentials
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: woodpecker-secrets
  namespace: woodpecker
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: woodpecker-secrets
    creationPolicy: Owner
  data:
    - secretKey: WOODPECKER_GITEA_CLIENT
      remoteRef:
        key: secret/tinai/woodpecker
        property: gitea_client_id
    - secretKey: WOODPECKER_GITEA_SECRET
      remoteRef:
        key: secret/tinai/woodpecker
        property: gitea_client_secret
    - secretKey: WOODPECKER_AGENT_SECRET
      remoteRef:
        key: secret/tinai/woodpecker
        property: agent_secret
    - secretKey: WOODPECKER_DATABASE_DATASOURCE
      remoteRef:
        key: secret/tinai/woodpecker
        property: database_url
